#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
验证加速运动正电荷产生加速度反向引力场的公式

公式：E_theta = (-q/(4*pi*epsilon0*c**2*r)) * (A × r_hat)

验证维度：
1. 核心公式计算验证
2. 横向电场推导验证
3. 磁场与引力场关系验证
4. 量纲分析验证
5. 方向关系验证
6. 衰减规律验证
7. 实验关联性验证
"""

# 导入模块化组件
from core.field_calculator import FieldCalculator
from visualization.field_visualizer import (
    plot_electric_field_distribution,
    plot_experiment_simulation,
    plot_3d_vector_visualization,
    plot_tokamak_z_pinch_simulation,
    plot_b_v1_classical_comparison
)
import numpy as np

# 保持向后兼容性，定义FieldVerifier类作为FieldCalculator的别名
class FieldVerifier(FieldCalculator):
    """场验证器类（向后兼容）"""
    pass

# 主函数
def main():
    """主函数"""
    print("=== Verification of Gravitational Field Formula Generated by Accelerating Positive Charges ===")
    print()
    
    # Create verifier
    verifier = FieldVerifier()
    
    # Run comprehensive verification
    results = verifier.run_comprehensive_verification()
    
    # Print dimension analysis verification result
    print("1. Dimension Analysis Verification:")
    print(f"   Dimension consistent: {results['dimension_analysis_verification']}")
    print()
    
    # 打印测试用例结果
    print("2. Multiple Test Cases Verification:")
    print(f"   Total test cases: {results['total_test_cases']}")
    print(f"   Passed test cases: {results['passed_test_cases']}")
    print()
    
    # 打印每个测试用例的详细结果
    for case in results['test_case_results']:
        print(f"   Test Case {case['test_case']}:")
        print(f"      Status: {case['verification_status']}")
        if case['verification_status'] == "passed":
            print(f"      Parameters: Charge={case['parameters']['charge']:.2e} C, Acceleration={case['parameters']['acceleration']:.2e} m/s², Distance={case['parameters']['distance']:.2f} m, Angle={case['parameters']['angle']:.2f} rad")
            print(f"      Transverse E-field magnitude: {case['core_formula_verification']['transverse_electric_field_magnitude']:.2e} V/m")
            print(f"      Magnetic field magnitude: {case['magnetic_field_verification']['magnetic_field_magnitude']:.2e} T")
            print(f"      Follows 1/r decay law: {case['decay_law_verification']['follows_1_over_r_law']}")
            # Print B_v1 formula verification results
            print(f"      B_v1 formula verification:")
            print(f"        Consistent with classical electrodynamics: {case['b_v1_formula_verification']['consistent_with_classical_electrodynamics']}")
            print(f"        Consistent with far-field approximation: {case['b_v1_formula_verification']['consistent_with_far_field_approximation']}")
            print(f"        Perpendicular to gravitational field: {case['b_v1_formula_verification']['perpendicular_to_gravitational_field']}")
            print(f"        Perpendicular to radial direction: {case['b_v1_formula_verification']['perpendicular_to_radial_direction']}")
            print(f"        Classical B-field magnitude: {case['b_v1_formula_verification']['classical_magnitude']:.2e} T")
            print(f"        Far-field B-field magnitude: {case['b_v1_formula_verification']['far_field_approximation_magnitude']:.2e} T")
        else:
            print(f"      Error message: {case['error_message']}")
        print()
    
    # 绘制电场分布（使用第一个测试用例的参数）
    print("3. Electric Field Distribution Visualization:")
    r_values = np.linspace(0.1, 10, 100)
    plot_electric_field_distribution(verifier, 1.6e-19, 1e10, r_values, np.pi/2)
    
    # 绘制 B_v1 公式与经典电动力学的对比
    print("4. B_v1 Formula vs Classical Electrodynamics Comparison:")
    plot_b_v1_classical_comparison(verifier, 1.6e-19, 1e10, r_values, np.pi/2)
    
    # 绘制实验模拟结果（使用第一个测试用例的结果）
    if results['test_case_results'] and results['test_case_results'][0]['verification_status'] == "passed":
        print("5. Experiment Simulation Result Visualization:")
        plot_experiment_simulation(results['test_case_results'][0]['experiment_simulation'])
    
    # 绘制3D矢量可视化
    print("6. 3D Vector Visualization:")
    # 使用第一个测试用例的参数
    test_case_params = [1.6e-19, 1e10, 1.0, np.pi/2, [1, 0, 0], [0, 1, 0]]
    q, a, r, theta, a_direction, r_hat_direction = test_case_params
    plot_3d_vector_visualization(verifier, q, a, r, a_direction, r_hat_direction)
    
    # 绘制托卡马克Z箍缩实验模拟
    print("7. Tokamak Z-pinch Experiment Simulation:")
    # 使用合理的托卡马克实验参数
    tokamak_params = {
        'current': 1e6,  # 1 MA
        'current_change_rate': 1e12,  # 1e12 A/s
        'plasma_radius': 0.1,  # 0.1 m
        'distance': 0.5  # 0.5 m
    }
    tokamak_results = verifier.simulate_tokamak_z_pinch_experiment(
        tokamak_params['current'],
        tokamak_params['current_change_rate'],
        tokamak_params['plasma_radius'],
        tokamak_params['distance']
    )
    plot_tokamak_z_pinch_simulation(tokamak_results)
    
    # 验证总结
    all_passed = results['dimension_analysis_verification'] and (results['passed_test_cases'] == results['total_test_cases'])
    
    print("=== Verification Summary ===")
    print(f"All verifications passed: {all_passed}")
    print(f"Passed test cases: {results['passed_test_cases']}/{results['total_test_cases']}")
    
    if all_passed:
        print("✓ Acceleration motion positive charge generating gravitational field formula verification passed!")
    else:
        print("✗ Some verifications failed, please check parameters and derivation process.")

if __name__ == "__main__":
    main()
