# -*- coding: utf-8 -*-
import sys
import io
import os

# Ensure UTF-8 encoding for standard output
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# Set environment variable to ensure proper matplotlib rendering
os.environ['PYTHONIOENCODING'] = 'utf-8'

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch
from matplotlib.path import Path
import matplotlib.colors as mcolors
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

# Configure matplotlib for better rendering with Chinese support
plt.rcParams.update({
    'text.usetex': False,
    'mathtext.fontset': 'cm',
    'mathtext.default': 'it',
    'axes.unicode_minus': False,
    'font.family': ['SimHei', 'WenQuanYi Micro Hei', 'Heiti TC', 'serif', 'DejaVu Serif'],
    'font.serif': ['SimHei', 'WenQuanYi Micro Hei', 'Heiti TC', 'Computer Modern', 'Times New Roman', 'DejaVu Serif'],
    'figure.facecolor': 'white',
    'savefig.facecolor': 'white',
    'figure.autolayout': True
})

# Set Nature style
plt.style.use('default')

class NatureStylePlotter:
    """Create Nature-style scientific visualizations"""
    
    def __init__(self):
        # Nature journal common color palette
        self.nature_colors = {
            'blue': '#0173B2',
            'cyan': '#029E73', 
            'green': '#009E73',
            'yellow': '#D55E00',
            'orange': '#E69F00',
            'red': '#CC78BC',
            'purple': '#56B4E9'
        }
        # Set default parameters
        self.figsize = (8, 6)
        self.dpi = 300
    
    def vector_potential_2d(self, output_file="vector_potential_2d.png"):
        """Generate 2D vector potential field visualization"""
        
        # Create grid
        x = np.linspace(-2, 2, 20)
        y = np.linspace(-2, 2, 20)
        X, Y = np.meshgrid(x, y)
        
        # Calculate vector potential (simulating magnetic vector potential from current loop)
        r = np.sqrt(X**2 + Y**2)
        r[r < 0.1] = 0.1  # Avoid division by zero
        
        # Vector potential A components (in x-y plane, A only has z component)
        # For visualization, we represent it as vectors circling the center
        theta = np.arctan2(Y, X)
        A_x = -Y / (r**2)
        A_y = X / (r**2)
        
        # Calculate B field (curl)
        B_z = (X**2 - Y**2) / r**4 * 2  # Approximate calculation
        
        # Create figure
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5), dpi=self.dpi)
        
        # Plot vector potential field
        stream = ax1.streamplot(X, Y, A_x, A_y, density=1.5, color=self.nature_colors['blue'], linewidth=1)
        ax1.set_title('Vector Potential Field (\\vec{A})', fontsize=14)
        ax1.set_xlabel('x', fontsize=12)
        ax1.set_ylabel('y', fontsize=12)
        ax1.set_aspect('equal')
        ax1.grid(False)
        
        # Plot B field (generated by curl of A)
        contour = ax2.contourf(X, Y, B_z, 20, cmap='viridis')
        cbar = plt.colorbar(contour, ax=ax2)
        cbar.set_label('B_z Intensity', fontsize=12)
        ax2.set_title('Magnetic Induction Field (\\vec{B} = f\\nabla\\times\\vec{A})', fontsize=14)
        ax2.set_xlabel('x', fontsize=12)
        ax2.set_ylabel('y', fontsize=12)
        ax2.set_aspect('equal')
        ax2.grid(False)
        
        # Add equation explanation
        fig.text(0.5, 0.01, 'Vector Potential Equation: \\nabla \\times \\vec{A} = \\frac{\\vec{B}}{f}', 
                 ha='center', fontsize=14, fontweight='bold')
        
        plt.tight_layout(rect=[0, 0.05, 1, 0.95])
        # Ensure output directory exists
        output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'visualizations')
        os.makedirs(output_dir, exist_ok=True)
        # Save with full path
        full_output_path = os.path.join(output_dir, output_file)
        plt.savefig(full_output_path, dpi=self.dpi, bbox_inches='tight')
        plt.close()
        print(f"2D vector potential visualization saved to: {full_output_path}")
    
    def vector_potential_3d(self, output_file="vector_potential_3d.png"):
        """Generate 3D magnetic vector potential field visualization"""
        
        # Create figure
        fig = plt.figure(figsize=(10, 8), dpi=self.dpi)
        ax = fig.add_subplot(111, projection='3d')
        
        # Create grid
        x = np.linspace(-1.5, 1.5, 15)
        y = np.linspace(-1.5, 1.5, 15)
        X, Y = np.meshgrid(x, y)
        
        # z=0 plane
        Z = np.zeros_like(X)
        
        # Calculate magnetic vector potential components (current along z-axis)
        r = np.sqrt(X**2 + Y**2)
        r[r < 0.1] = 0.1
        
        # Magnetic vector potential components
        A_x = -Y / r**2
        A_y = X / r**2
        A_z = np.zeros_like(X)
        
        # Calculate vector magnitude for color mapping
        A_mag = np.sqrt(A_x**2 + A_y**2 + A_z**2)
        
        # Plot vector field
        quiver = ax.quiver(X, Y, Z, A_x, A_y, A_z, 
                           length=0.3, normalize=True, 
                           color=self.nature_colors['blue'], alpha=0.7)
        
        # Add current direction indicator (using 3D arrow)
        ax.quiver(0, 0, -1, 0, 0, 2, color=self.nature_colors['red'], 
                  arrow_length_ratio=0.15, linewidth=3)
        ax.text(0, 0, 1.2, 'Current Direction', color=self.nature_colors['red'], fontsize=12)
        
        # Set title and labels
        ax.set_title('3D Magnetic Vector Potential Field Visualization', fontsize=14)
        ax.set_xlabel('x', fontsize=12)
        ax.set_ylabel('y', fontsize=12)
        ax.set_zlabel('z', fontsize=12)
        
        # Set viewing angle
        ax.view_init(elev=30, azim=45)
        
        # Add equation
        fig.text(0.5, 0.01, 'Vector Potential Equation: \\nabla \\times \\vec{A} = \\frac{\\vec{B}}{f}', 
                 ha='center', fontsize=14, fontweight='bold')
        
        # Ensure output directory exists
        output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'visualizations')
        os.makedirs(output_dir, exist_ok=True)
        # Save with full path
        full_output_path = os.path.join(output_dir, output_file)
        plt.tight_layout(rect=[0, 0.05, 1, 0.95])
        plt.savefig(full_output_path, dpi=self.dpi, bbox_inches='tight')
        plt.close()
        print(f"3D magnetic vector potential visualization saved to: {full_output_path}")
    
    def curl_visualization(self, output_file="curl_visualization.png"):
        """Visualize curl operation \\nabla\\times\\vec{A}"""
        
        # Create figure
        fig = plt.figure(figsize=(10, 7), dpi=self.dpi)
        
        # Plot relationship between vector field and its curl
        ax = fig.add_subplot(111)
        
        # Create a simple circular vector field to represent A
        theta = np.linspace(0, 2*np.pi, 20)
        r = 1.0
        x = r * np.cos(theta)
        y = r * np.sin(theta)
        
        # Vector directions
        u = -y
        v = x
        
        # Normalize vectors
        mag = np.sqrt(u**2 + v**2)
        u = u/mag
        v = v/mag
        
        # Plot circular vector field
        ax.quiver(x, y, u, v, color=self.nature_colors['blue'], label='Vector Potential \\vec{A}')
        
        # Plot curl direction (perpendicular to the plane)
        center_x, center_y = 0, 0
        circle = plt.Circle((center_x, center_y), 1.5, fill=False, 
                           color=self.nature_colors['red'], linestyle='--',
                           label='Curl Direction (\\nabla\\times\\vec{A})')
        ax.add_patch(circle)
        
        # Add curl direction indicator arrow
        arrow_angle = np.pi/4
        arrow_x = 1.5 * np.cos(arrow_angle)
        arrow_y = 1.5 * np.sin(arrow_angle)
        ax.annotate('', xy=(arrow_x, arrow_y), xytext=(0.8*arrow_x, 0.8*arrow_y),
                    arrowprops=dict(facecolor=self.nature_colors['red'], shrink=0, width=2, headwidth=10))
        ax.text(1.7 * np.cos(arrow_angle), 1.7 * np.sin(arrow_angle), "+z", 
                color=self.nature_colors['red'], fontsize=12, fontweight='bold')
        
        # Add equation explanation
        ax.text(0, -2.5, 'The direction of \\nabla\\times\\vec{A} is perpendicular to the plane of \\vec{A}', 
                ha='center', fontsize=12)
        
        # Set title and labels
        ax.set_title('Visualization of Curl Operation \\nabla\\times\\vec{A}', fontsize=14)
        ax.set_xlabel('x', fontsize=12)
        ax.set_ylabel('y', fontsize=12)
        ax.set_xlim(-2, 2)
        ax.set_ylim(-3, 2)
        ax.set_aspect('equal')
        ax.legend(loc='upper right')
        
        # Add equation
        fig.text(0.5, 0.01, 'Curl Operation: \\nabla \\times \\vec{A} = \\frac{\\vec{B}}{f}', 
                 ha='center', fontsize=14, fontweight='bold')
        
        # Ensure output directory exists
        output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'visualizations')
        os.makedirs(output_dir, exist_ok=True)
        # Save with full path
        full_output_path = os.path.join(output_dir, output_file)
        plt.tight_layout(rect=[0, 0.05, 1, 0.95])
        plt.savefig(full_output_path, dpi=self.dpi, bbox_inches='tight')
        plt.close()
        print(f"Curl visualization saved to: {full_output_path}")
    
    def potential_energy_relationship(self, output_file="potential_energy_relationship.png"):
        """Visualize the relationship between vector potential and energy"""
        
        # Create figure
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6), dpi=self.dpi)
        
        # Left: Vector potential distribution
        r = np.linspace(0.1, 3, 100)
        A_r = 1/r  # Simple 1/r potential
        
        ax1.plot(r, A_r, color=self.nature_colors['blue'], linewidth=2)
        ax1.set_title('Vector Potential Distribution', fontsize=14)
        ax1.set_xlabel('r', fontsize=12)
        ax1.set_ylabel('|\\vec{A}|', fontsize=12)
        ax1.grid(True, linestyle='--', alpha=0.7)
        
        # Right: Energy relationship
        E_r = 1/r**2  # Energy is proportional to A^2
        
        ax2.plot(r, E_r, color=self.nature_colors['red'], linewidth=2)
        ax2.set_title('Energy Distribution', fontsize=14)
        ax2.set_xlabel('r', fontsize=12)
        ax2.set_ylabel('Energy Density', fontsize=12)
        ax2.grid(True, linestyle='--', alpha=0.7)
        
        # Add relationship equation
        fig.text(0.5, 0.01, 'Energy Relationship: E \\propto |\\vec{A}|^2', 
                 ha='center', fontsize=14, fontweight='bold')
        
        # Ensure output directory exists
        output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'visualizations')
        os.makedirs(output_dir, exist_ok=True)
        # Save with full path
        full_output_path = os.path.join(output_dir, output_file)
        plt.tight_layout(rect=[0, 0.05, 1, 0.95])
        plt.savefig(full_output_path, dpi=self.dpi, bbox_inches='tight')
        plt.close()
        print(f"Potential-energy relationship visualization saved to: {full_output_path}")

if __name__ == "__main__":
    # Create visualization directory
    output_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'visualizations')
    os.makedirs(output_dir, exist_ok=True)
    
    # Initialize plotter
    plotter = NatureStylePlotter()
    
    # Generate various visualizations
    plotter.vector_potential_2d(os.path.join(output_dir, 'vector_potential_2d.png'))
    plotter.vector_potential_3d(os.path.join(output_dir, 'vector_potential_3d.png'))
    plotter.curl_visualization(os.path.join(output_dir, 'curl_visualization.png'))
    plotter.potential_energy_relationship(os.path.join(output_dir, 'potential_energy_relationship.png'))
    
    print("All vector potential visualization images have been successfully generated!")